version: "3.8"

services:
  auth-microservice-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - NODE_ENV=development
      - MONGO_DB_URI=mongodb://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST_NAME}:${DATABASE_PORT}/?authMechanism=${AUTH_MECANISM}&authSource=${AUTH_SOURCE}
    container_name: api
    depends_on:
      - auth-microservice-db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.development
      - .env.production
    restart: unless-stopped
  
  auth-microservice-db:
      image: mongo
      container_name: database
      ports:
        - ${DATABASE_PORT}:${DATABASE_PORT}
      volumes:
          - mongo-data:/data/db

volumes:
    mongo-data: {}